theme: jekyll-theme-midnight
title: Janell's Portfolio
description: An Example Portfolio (Introduction to Programming)
logo: https://avatars1.githubusercontent.com/u/18712834?s=400&u=7a3229acbe5a3b42107c786e44accdbf0707d746&v=4
